# Generated by Django 5.2.13 on 2026-05-09 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('destination', models.CharField(db_index=True, max_length=120)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price per traveler.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['destination', 'title'],
                'indexes': [models.Index(fields=['destination', 'is_active'], name='packages_pa_destina_7b258b_idx'), models.Index(fields=['city', 'is_active'], name='packages_pa_city_14b653_idx'), models.Index(fields=['price'], name='packages_pa_price_3806c5_idx')],
            },
        ),
    ]
