# Generated by Django 5.2.13 on 2026-04-18 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('transports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('hotel', 'Hotel'), ('transport', 'Transport')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('guests_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rooms_reserved', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('passengers_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('special_request', models.TextField(blank=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotels.hotel')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transports.transport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-reserved_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='reservation_user_id_b23f11_idx'), models.Index(fields=['reservation_type', 'status'], name='reservation_reserva_9f9c2c_idx'), models.Index(fields=['reserved_at'], name='reservation_reserve_0c8c36_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reservation_type', 'hotel'), ('hotel__isnull', False), ('transport__isnull', True)), models.Q(('reservation_type', 'transport'), ('hotel__isnull', True), ('transport__isnull', False)), _connector='OR'), name='reservation_type_matches_related_object'), models.CheckConstraint(condition=models.Q(('check_in_date__isnull', True), ('check_out_date__isnull', True), ('check_out_date__gt', models.F('check_in_date')), _connector='OR'), name='reservation_checkout_after_checkin')],
            },
        ),
    ]
