# Generated by Django 5.2.13 on 2026-05-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('packages', '0001_initial'),
        ('reservations', '0001_initial'),
        ('transports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reservation_type_matches_related_object',
        ),
        migrations.AddField(
            model_name='reservation',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='packages.package'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('transport', 'Transport'), ('package', 'Package')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['payment_status'], name='reservation_payment_060592_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reservation_type', 'hotel'), ('hotel__isnull', False), ('transport__isnull', True), ('package__isnull', True)), models.Q(('reservation_type', 'transport'), ('hotel__isnull', True), ('transport__isnull', False), ('package__isnull', True)), models.Q(('reservation_type', 'package'), ('hotel__isnull', True), ('transport__isnull', True), ('package__isnull', False)), _connector='OR'), name='reservation_type_matches_related_object'),
        ),
    ]
