# Generated by Django 5.2.13 on 2026-04-18 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Hotel rating on a 0 to 5 scale.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('number_of_rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['city', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_rooms__lte', models.F('number_of_rooms'))), name='hotel_available_rooms_lte_total_rooms')],
            },
        ),
    ]
