# Generated by Django 5.2.13 on 2026-04-18 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus')], max_length=20)),
                ('company', models.CharField(max_length=150)),
                ('departure_city', models.CharField(db_index=True, max_length=120)),
                ('arrival_city', models.CharField(db_index=True, max_length=120)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.DurationField(blank=True, help_text='Auto-calculated from departure and arrival times if left empty.', null=True)),
                ('service_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First'), ('vip', 'VIP')], default='economy', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ['departure_time', 'company'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='transports__type_a12346_idx'), models.Index(fields=['departure_city', 'arrival_city'], name='transports__departu_ba0126_idx'), models.Index(fields=['departure_time'], name='transports__departu_a1f3d4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('total_seats'))), name='transport_available_seats_lte_total_seats'), models.CheckConstraint(condition=models.Q(('arrival_time__gt', models.F('departure_time'))), name='transport_arrival_after_departure')],
            },
        ),
    ]
